version: "2"

services:
#  webdict:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - SKIP_BACKEND_TEST
#    image: macyan13/webdict:dev
#    container_name: "webdict"
#    hostname: "webdict-dev"
#
#    # uncomment to expose directly (no proxy)
#    ports:
#      - "4000:${PORT}"
#
#    environment:
#      - AUTH_SECRET=secret_string
#      - PORT=4000
#      - DEBUG=1
#      - GIN_MODE=debug

  mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/