version: "2"

services:
  webdict:
    build: .
    image: macyan13/webdict:latest
    container_name: "webdict"
    hostname: "webdict"
    restart: always
    mem_limit: ${APP_MEMORY_LIMIT}

    # uncomment to expose directly (no proxy)
    ports:
      - "4000:${PORT}"

    environment:
      - APP_MEMORY_LIMIT=${APP_MEMORY_LIMIT:-512m}
      - AUTH_TTL_AUTH
      - AUTH_TTL_REFRESH
      - AUTH_TTL_COOKIE
      - AUTH_SECRET
      - ADMIN_PASSWD
      - ADMIN_EMAIL
      - PORT
      - URL
      - DEBUG
      - GIN_MODE
      - MONGO_DB
      - MONGO_HOST
      - MONGO_PORT