version: "3"

services:
  webdict:
    build: .
    image: macyan13/webdict:latest
    container_name: "webdict"
    hostname: "webdict"
    restart: always
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 512m

    # uncomment to expose directly (no proxy)
    ports:
      - "4000:4000"

    environment:
      - AUTH_TTL_AUTH
      - AUTH_TTL_REFRESH
      - AUTH_TTL_COOKIE
      - AUTH_SECRET
      - ADMIN_PASSWD
      - ADMIN_EMAIL
      - PORT
      - URL
      - DEBUG
      - GIN_MODE
      - MONGO_DB
      - MONGO_HOST
      - MONGO_PORT

  mongo:
    image: mongo:4.2.3
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}