run:
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor
    - pkg/store/inmemory

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
    disabled-checks:
#      - wrapperFunc
# Disable it for now, maybe fix and remove later
      - hugeParam
#      - rangeValCopy

linters:
  disable-all: true
  enable:
    - bodyclose
    - megacheck
    - revive
    - govet
    - unconvert
    - megacheck
#    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
#    - varcheck
#    - deadcode
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - exportloopref
    - gocritic
    - nakedret
    - gosimple
    - prealloc
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
#    - text: "at least one file in a package should have a package comment"
#      linters:
#        - stylecheck
#    - text: "should have a package comment, unless it's in another file for this package"
#      linters:
#        - golint
#  exclude-use-default: false
