### Generate Authentication token
POST {{host}}/v1/api/auth/signin
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
client.global.set("auth_token", response.body.accessToken)
client.global.set("auth_type", response.body.type)
 %}

### Create Translation
POST {{host}}/v1/api/translations
Content-Type: application/json
Authorization: {{auth_type}} {{auth_token}}

{
  "translation": "Give it a shot",
  "text": "Попробовать",
  "example": "Just give it a shot",
  "transcription": "[n/a]"
}

### Get the list of last created translations
GET {{host}}/v1/api/translations/last?limit=10
Authorization: {{auth_type}} {{auth_token}}

