// Code generated by mockery v2.14.0. DO NOT EDIT.

package translation

import mock "github.com/stretchr/testify/mock"

// mockery --name=Repository --filename=repository_mock.go --output=./ --structname=MockRepository --inpackage
// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: translation
func (_m *MockRepository) Create(translation Translation) error {
	ret := _m.Called(translation)

	var r0 error
	if rf, ok := ret.Get(0).(func(Translation) error); ok {
		r0 = rf(translation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id, authorId
func (_m *MockRepository) Delete(id string, authorId string) error {
	ret := _m.Called(id, authorId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, authorId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id, authorId
func (_m *MockRepository) Get(id string, authorId string) (Translation, error) {
	ret := _m.Called(id, authorId)

	var r0 Translation
	if rf, ok := ret.Get(0).(func(string, string) Translation); ok {
		r0 = rf(id, authorId)
	} else {
		r0 = ret.Get(0).(Translation)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, authorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: translation
func (_m *MockRepository) Update(translation Translation) error {
	ret := _m.Called(translation)

	var r0 error
	if rf, ok := ret.Get(0).(func(Translation) error); ok {
		r0 = rf(translation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t mockConstructorTestingTNewMockRepository) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
