name: Go

on:
  pull_request:
    paths:
      - ".github/workflows/*"
      - "backend/**"

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Display Go version
        run: go version

      - name: Test
        working-directory: ./backend
        run: go test -v ./...

      - name: Build
        working-directory: ./backend
        run: go build -v ./...
